# Generated by Django 5.1.7 on 2025-03-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waazi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'verbose_name_plural': 'Listening Histories'},
        ),
        migrations.AlterModelOptions(
            name='scholar',
            options={'verbose_name_plural': 'Scholars'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name_plural': 'User Favorites'},
        ),
        migrations.AlterModelOptions(
            name='waazi',
            options={'verbose_name_plural': 'Waazis'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Tafsiri', 'Tafsiri'), ('Fiqhu', 'Fiqhu'), ('Aqida', 'Aqida'), ('Tarihi', 'Tarihi'), ('Hadisi', 'Hadisi'), ('Sira', 'Sira'), ('Kyawawan Halaye', 'Kyawawan Halaye'), ("Karatun Alƙur'ani", "Karatun Alƙur'ani"), ("Fiqhun Shari'a", "Fiqhun Shari'a"), ('Ruhaniya', 'Ruhaniya')], max_length=100, unique=True),
        ),
    ]
